name: make a mesa
on:
   workflow_dispatch:
jobs:
  job-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: download archives
        run: |
          sudo apt-get install git wget meson ninja* python3 xwayland clang cmake gcc
          pip3 install mako setuptools
      - name: prepar achivers 
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r27c-linux.zip
          unzip android-ndk-r27c-linux.zip
          mv android-ndk-r27c /home/runner
          export NKD=/home/runner/android-ndk-r27c
          export PATH=$PATH:$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin
          export CC=clang
          export CXX=clang++
          mkdir /home/runner/mesa
          git clone https://github.com/anonymususer04/mesa-Panfork-android.git
          cd mesa-Panfork-android
          LDFLAGS=" -L$PREFIX/bin -l:libandroid-shmem.a -llog -Wl,--undefined-version"  meson  build -Dgallium-drivers=panfrost,swrast -Dvulkan-drivers= -Dbuildtype=release -Dllvm=disabled -Dplatforms=x11,wayland  -Dprefix=/home/runner/mesa && ninja -C build install
          tar -cvf /home/runner/mesa-panfork.tar.gz /home/runner/mesa
      - name: dispatch
        uses: softprops/action-gh-release@v2
        with:
          name: "Mesa Panfork"
          tag-name: mesa-panfork
          prerelease: true
          files: |
            /home/runner/mesa-panfork.tar.gz
      
      

